### ISSUE TITLE
Simplify i18n process: separate properties from birds

### ISSUE THREAD

**Issue by erikhuizinga** [navarog/wingsearch#9]
Various birds share the same (or similar) properties. It would help i18n if translators would translate properties instead of birds. Your website should know which properties belong to which birds. That would help translators, because there are less properties to translate than birds.

Note that some properties comprise of multiple parts. Some of these subparts are shared between even more birds. Therefore I suggest to have translators translate the subparts. This suggestion assumes that all languages use the same subparts of properties, and the same combinations of these subparts for all birds.

**Comment by navarog** [comment]
Thanks for the suggestion. Apart from putting the constraint of using the same subparts on all languages, I see another problem in rising complexity of finding the right part to translate. With the current setup, user can simply find the bird he is going to translate and that's it, pretty simple. I am afraid some might get discouraged by writing when they do not see the obvious way and have to search for the exact meaning of the text instead of the bird. It also adds additional complexity on my side, more additional steps to take when expansions with new texts come. 

With the oceania expansion, there are 356 birds to translate (counting also birds with no power) with 226 unique power texts. There are 15 birds with the 'Draw 2 new bonus cards and keep 1.' power and few other, which are quite often and could be easily copied to the corresponding birds, but 175 of power text have only one occurence. Mean of this distribution is 1.5 and median 1.
![image](https://user-images.githubusercontent.com/22467181/99253285-c8e57200-2810-11eb-8232-c574d2046296.png)
Therefore, people would have to write most of the bird powers anyway and search for those cards.
